// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ParkingGent.Api.Data;

#nullable disable

namespace ParkingGent.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260929082331_Fietsenstallingen")]
    partial class Fietsenstallingen
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ParkingGent.Api.Domain.Measurement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AvailableSpaces")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MeasuredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("OccupancyPct")
                        .HasColumnType("smallint");

                    b.Property<int>("ParkingId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MeasuredAtUtc");

                    b.HasIndex("ParkingId", "MeasuredAtUtc")
                        .IsUnique();

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("ParkingGent.Api.Domain.Parking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasLiveData")
                        .HasColumnType("boolean");

                    b.Property<bool?>("InLowEmissionZone")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsFree")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OpeningHours")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Operator")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Kind");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Parkings");
                });

            modelBuilder.Entity("ParkingGent.Api.Domain.ParkingStatus", b =>
                {
                    b.Property<int>("ParkingId")
                        .HasColumnType("integer");

                    b.Property<int>("AvailableSpaces")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPlausible")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("MeasuredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("OccupancyPct")
                        .HasColumnType("smallint");

                    b.Property<string>("SourceTrend")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("TemporarilyClosed")
                        .HasColumnType("boolean");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("integer");

                    b.HasKey("ParkingId");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("ParkingGent.Api.Domain.SyncRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CatalogueCount")
                        .HasColumnType("integer");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<int>("LiveCount")
                        .HasColumnType("integer");

                    b.Property<int>("MeasurementsAdded")
                        .HasColumnType("integer");

                    b.Property<int>("MeasurementsPruned")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("Ok")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("StartedUtc");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("ParkingGent.Api.Domain.Measurement", b =>
                {
                    b.HasOne("ParkingGent.Api.Domain.Parking", "Parking")
                        .WithMany("Measurements")
                        .HasForeignKey("ParkingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parking");
                });

            modelBuilder.Entity("ParkingGent.Api.Domain.ParkingStatus", b =>
                {
                    b.HasOne("ParkingGent.Api.Domain.Parking", "Parking")
                        .WithOne("Status")
                        .HasForeignKey("ParkingGent.Api.Domain.ParkingStatus", "ParkingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parking");
                });

            modelBuilder.Entity("ParkingGent.Api.Domain.Parking", b =>
                {
                    b.Navigation("Measurements");

                    b.Navigation("Status");
                });
#pragma warning restore 612, 618
        }
    }
}
